export const CHARACTERS = {
  sarah:  { name: 'Sarah Chen',       role: 'EHS Manager',   initials: 'SC', color: '#626DF9' },
  mike:   { name: 'Mike Rodriguez',   role: 'Line Worker',   initials: 'MR', color: '#D32F2F' },
  priya:  { name: 'Priya Patel',      role: 'Supervisor',    initials: 'PP', color: '#2E7D32' },
  james:  { name: 'James Thompson',   role: 'Investigator',  initials: 'JT', color: '#ED6C02' },
  anya:   { name: 'Anya Kowalski',    role: 'CAPA Owner',    initials: 'AK', color: '#8b5cf6' },
};

export const SETTINGS = {
  chemPlant:   { name: 'Westfield Chemical Plant',    icon: 'factory' },
  construction:{ name: 'Metro Construction Site 7',   icon: 'factory' },
  warehouse:   { name: 'Lakeside Distribution Center',icon: 'factory' },
  office:      { name: 'Greenfield Office Campus',    icon: 'factory' },
};

export const STORIES = [
  {
    id: 'injury_chemical_splash',
    incidentType: 'injury',
    title: 'The Chemical Splash',
    subtitle: 'Learn injury reporting through a realistic chemical exposure scenario',
    setting: SETTINGS.chemPlant,
    characters: ['mike', 'priya', 'sarah'],
    estimatedMinutes: 8,
    difficulty: 'beginner',
    color: '#D32F2F',
    icon: 'fire',
    coversModules: ['incidents', 'investigations', 'capas'],
    learningOutcomes: [
      'Fill out the injury-specific form with body map and PPE',
      'Use the risk matrix to classify severity',
      'Understand OSHA recordability for medical treatment cases',
    ],
    chapters: [
      { title: 'The Scene', cards: [0, 1] },
      { title: 'The Incident', cards: [2] },
      { title: 'Reporting It', cards: [3, 4, 5] },
      { title: 'The Response', cards: [6, 7] },
      { title: 'The Outcome', cards: [8, 9] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'Westfield Chemical Plant — Lab 2',
        content: 'It\'s 9:15 AM on a Tuesday. Westfield Chemical Plant is in full production. In Lab 2, operators handle concentrated acids daily as part of their quality control process.',
        character: 'mike',
        quote: 'I\'ve been on the acid transfer line for three years. You know the routine by heart — gown, gloves, face shield, slow pour.',
        setting: 'chemPlant',
      },
      {
        type: 'narrative',
        title: 'Meet the Team',
        content: 'Every incident in this system flows through people. Here\'s who you\'ll meet in this story — each plays a role in the incident lifecycle.',
        characters: ['mike', 'priya', 'sarah'],
        bullets: [
          { char: 'mike', text: 'Reports the incident and provides first-hand details' },
          { char: 'priya', text: 'Triages the report and assigns an investigation' },
          { char: 'sarah', text: 'Oversees the CAPA and verifies closure' },
        ],
      },
      {
        type: 'narrative',
        title: 'The Hose Fitting Fails',
        content: 'Mike is transferring sulfuric acid from an IBC to a smaller container. He\'s following every step of the SOP. But the brass fitting on the transfer hose — installed six months ago — has corroded. It cracks under pressure.',
        character: 'mike',
        quote: 'I heard a pop, then felt the burn before I saw it. Acid splashed above my glove line onto my forearm. I hit the eyewash station immediately.',
        highlight: 'This is a workplace injury — contact with a chemical substance causing a chemical burn to the forearm.',
      },
      {
        type: 'annotation',
        title: 'Step 1: Open the Report Wizard',
        content: 'The first thing Mike (or his supervisor) does is open the Incident Report Wizard. You can access this from any page using the "Report" button.',
        annotation: 'In the wizard, you\'ll fill in: what happened, when, where, and who was involved. The system guides you step-by-step.',
        tip: 'You can also use voice reporting — describe what happened verbally and the AI extracts the fields for you.',
      },
      {
        type: 'annotation',
        title: 'Step 2: Select the Right Incident Type',
        content: 'The wizard shows 8 incident types. For Mike\'s situation, we select "Injury" — because physical harm occurred.',
        annotation: 'The type determines which specific form fields appear next. An injury asks about the body part, mechanism, and treatment. An illness would ask about exposure duration and work-relatedness.',
        highlightType: 'injury',
        tip: 'Not sure which type? Choose the closest match. You can always update it later during investigation.',
      },
      {
        type: 'exercise',
        title: 'Classify the Risk',
        content: 'Based on Mike\'s acid splash, use the risk matrix to classify the severity. Consider:\n\n• The splash was contained to the forearm\n• First aid was applied immediately\n• Medical treatment was required (beyond first aid)\n• No permanent damage expected',
        exerciseType: 'risk_matrix',
        correctLikelihood: 2,
        correctConsequence: 2,
        explanation: 'Likelihood "Possible" (acid transfers happen regularly, fittings can fail) × Consequence "Moderate" (medical treatment needed, no permanent disability) = **S3, Track B**. This triggers a light investigation with supervisor review.',
      },
      {
        type: 'lifecycle',
        title: 'What Happens Next',
        content: 'After Mike submits the report, the system routes it through the incident lifecycle. Here\'s exactly how this S3 Track B injury progresses:',
        stages: [
          { status: 'New', day: 'Day 0', actor: 'mike', description: 'Mike submits the incident report. System auto-classifies as S3, Track B.' },
          { status: 'Triage', day: 'Day 0', actor: 'priya', description: 'Priya receives a notification. She reviews the report and assigns James as investigator.' },
          { status: 'Investigating', day: 'Day 1-3', actor: 'james', description: 'James interviews Mike, inspects the hose fitting, runs a 5-Why analysis. Root cause: no scheduled replacement for corroding brass fittings.' },
          { status: 'Awaiting CAPA', day: 'Day 4', actor: 'james', description: 'James creates a CAPA: replace all brass fittings with PTFE-lined stainless steel. Assigns Anya as owner, due in 14 days.' },
          { status: 'Closed', day: 'Day 20', actor: 'sarah', description: 'Anya completes the replacement. Sarah verifies effectiveness — no recurrence. Incident closed.' },
        ],
      },
      {
        type: 'annotation',
        title: 'OSHA Recordability',
        content: 'Because Mike received medical treatment beyond first aid (the burn required professional wound care), this incident is OSHA-recordable.',
        annotation: 'The system automatically flags recordable incidents and populates the OSHA 300 log and 301 form. Your EHS manager can generate these reports from the Reports module.',
        tip: 'First aid only (like applying a bandage) is NOT recordable. Medical treatment (prescription, stitches, professional care) IS recordable.',
      },
      {
        type: 'narrative',
        title: 'What We Learned',
        content: 'This scenario taught you the complete journey of a workplace injury through the system.',
        learnings: [
          'How to report an injury using the Report Wizard',
          'Selecting the correct incident type (Injury vs Illness)',
          'Using the risk matrix to classify severity (S3 Track B)',
          'How the lifecycle flows: New → Triage → Investigation → CAPA → Closed',
          'OSHA recordability criteria for medical treatment cases',
        ],
      },
      {
        type: 'narrative',
        title: 'What If?',
        content: 'Different outcomes change how the system handles the incident.',
        whatIfs: [
          { scenario: 'The acid hit Mike\'s eyes instead of his forearm', result: 'S2 Major, Track A — full investigation, likely RIDDOR reportable, immediate HSE notification.' },
          { scenario: 'The splash missed Mike entirely', result: 'Report as a Near Miss instead. Potential severity is still high, so it still warrants a Track A investigation.' },
          { scenario: 'The fitting failed but no acid was being transferred', result: 'Report as Unsafe Condition — proactive hazard identification before an incident occurs.' },
        ],
      },
    ],
  },

  {
    id: 'illness_coating_booth',
    incidentType: 'illness',
    title: 'The Coating Booth',
    subtitle: 'Understand occupational illness reporting and exposure tracking',
    setting: SETTINGS.chemPlant,
    characters: ['anya', 'james', 'sarah'],
    estimatedMinutes: 7,
    difficulty: 'beginner',
    color: '#9C27B0',
    icon: 'pulse',
    coversModules: ['incidents', 'investigations'],
    learningOutcomes: [
      'Distinguish illness from injury reporting',
      'Document exposure duration and work-relatedness',
      'Understand occupational disease patterns',
    ],
    chapters: [
      { title: 'The Scene', cards: [0] },
      { title: 'The Incident', cards: [1] },
      { title: 'Reporting It', cards: [2, 3] },
      { title: 'The Response', cards: [4] },
      { title: 'The Outcome', cards: [5] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'Coating Line B — Ventilation Trouble',
        content: 'Anya has been working on Coating Line B for the past three weeks. The coating process uses solvent-based paints in an enclosed booth with exhaust ventilation.',
        character: 'anya',
        quote: 'At first I thought the headaches were just from the shift pattern. But they got worse every day — always worse by afternoon. Then the dizziness started.',
      },
      {
        type: 'narrative',
        title: 'Connecting the Dots',
        content: 'After three weeks of worsening symptoms, Anya visits the occupational health nurse. The nurse notes that symptoms correlate with work shifts and recommends Anya report this as an occupational illness.',
        character: 'anya',
        quote: 'The nurse asked if anyone else on the line had similar symptoms. Turns out, two others had mentioned headaches but hadn\'t reported them.',
        highlight: 'This is an occupational illness — not a single event like an injury, but a condition that develops over time from workplace exposure.',
      },
      {
        type: 'annotation',
        title: 'Illness vs Injury — The Key Difference',
        content: 'In the Report Wizard, Anya selects "Illness" instead of "Injury." The form changes to ask illness-specific questions.',
        annotation: 'Illness reporting asks for: affected person, illness category (respiratory, skin, hearing, etc.), exposure duration, and whether the condition is work-related. Injury reporting asks for: body part, mechanism, treatment.',
        highlightType: 'illness',
        tip: 'Rule of thumb: if it happened in a moment (fall, cut, burn), it\'s an injury. If it developed over time (hearing loss, respiratory condition, repetitive strain), it\'s an illness.',
      },
      {
        type: 'exercise',
        title: 'Classify the Risk',
        content: 'Anya\'s respiratory symptoms from solvent exposure. Consider:\n\n• Multiple workers affected on the same line\n• Symptoms worsen with continued exposure\n• Ventilation system at 40% capacity\n• Condition is reversible with reduced exposure',
        exerciseType: 'risk_matrix',
        correctLikelihood: 3,
        correctConsequence: 2,
        explanation: 'Likelihood "Likely" (multiple workers affected, ongoing exposure) × Consequence "Moderate" (reversible condition requiring medical attention) = **S3, Track B**.',
      },
      {
        type: 'lifecycle',
        title: 'Investigation & Resolution',
        content: 'The investigation reveals the root cause and leads to systemic changes:',
        stages: [
          { status: 'New', day: 'Day 0', actor: 'anya', description: 'Anya submits the illness report. System flags it as S3, Track B.' },
          { status: 'Investigating', day: 'Day 1-5', actor: 'james', description: 'James investigates. Air monitoring confirms solvent levels 3x above PEL. Exhaust filters hadn\'t been replaced in 4 months.' },
          { status: 'Awaiting CAPA', day: 'Day 6', actor: 'james', description: 'Two CAPAs created: (1) Immediate filter replacement, (2) Monthly filter inspection schedule.' },
          { status: 'Closed', day: 'Day 30', actor: 'sarah', description: 'Follow-up air monitoring confirms levels below PEL. Workers\' symptoms resolved. Verified and closed.' },
        ],
      },
      {
        type: 'narrative',
        title: 'Key Takeaway',
        content: 'Occupational illnesses are often underreported because symptoms develop gradually. This system makes it easy to report patterns, not just events.',
        learnings: [
          'How illness reporting differs from injury reporting',
          'The importance of exposure duration and pattern recognition',
          'Why even mild symptoms should be reported early',
          'How one report can protect multiple workers',
        ],
      },
    ],
  },

  {
    id: 'nearmiss_falling_pallet',
    incidentType: 'nearmiss',
    title: 'The Falling Pallet',
    subtitle: 'Learn why near-miss reporting prevents tomorrow\'s injuries',
    setting: SETTINGS.warehouse,
    characters: ['mike', 'priya', 'james'],
    estimatedMinutes: 7,
    difficulty: 'beginner',
    color: '#ED6C02',
    icon: 'warning',
    coversModules: ['incidents', 'investigations', 'capas'],
    learningOutcomes: [
      'Understand potential severity vs actual outcome',
      'Learn Track A escalation for high-potential near-misses',
      'See how near-misses prevent future injuries',
    ],
    chapters: [
      { title: 'The Scene', cards: [0] },
      { title: 'The Incident', cards: [1] },
      { title: 'Reporting It', cards: [2, 3] },
      { title: 'The Response', cards: [4] },
      { title: 'The Outcome', cards: [5] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'Lakeside Distribution Center — Shift Change',
        content: 'It\'s 3:00 PM — shift changeover at the distribution center. Forklifts are moving between aisles, outbound trucks are loading, and foot traffic is at its peak.',
        character: 'mike',
        quote: 'I was reversing out of Aisle 14 when I misjudged the turn. The counterweight clipped the bottom racking upright.',
      },
      {
        type: 'narrative',
        title: 'Too Close for Comfort',
        content: 'The impact dislodges a loaded pallet from the third level of the racking. It falls 3 metres and crashes onto the floor — exactly where a picker had been walking 10 seconds earlier.',
        character: 'mike',
        quote: 'Nobody got hurt, but I won\'t forget the sound that pallet made hitting the concrete. That could have been someone.',
        highlight: 'No one was injured, but the potential outcome was catastrophic. This is a near-miss — and near-misses are the most valuable reports in the system.',
      },
      {
        type: 'annotation',
        title: 'Near-Miss: Report the Potential, Not Just the Result',
        content: 'Mike selects "Near Miss" in the wizard. The key question: what\'s the potential severity — not what actually happened, but what could have happened.',
        annotation: 'Near-miss forms ask about the hazard type and potential severity. The risk matrix should reflect the worst realistic outcome, not the actual (no injury) outcome.',
        highlightType: 'nearmiss',
        tip: 'A near-miss with life-threatening potential gets the same investigation as an actual serious injury. This is by design — the only difference was luck.',
      },
      {
        type: 'exercise',
        title: 'Classify the Potential Risk',
        content: 'A heavy pallet fell 3 metres in a pedestrian area. No one was hurt, but consider the potential:\n\n• A person was in the zone 10 seconds before\n• Loaded pallet (200+ kg) at head height\n• Peak foot traffic period\n• Potential for fatal crush injury',
        exerciseType: 'risk_matrix',
        correctLikelihood: 2,
        correctConsequence: 3,
        explanation: 'Likelihood "Possible" (forklifts operate near racking daily) × Consequence "Major" (potential fatal injury) = **S2, Track A**. Track A triggers a full investigation with a lead investigator assigned within 24 hours.',
      },
      {
        type: 'lifecycle',
        title: 'Full Investigation for a Near-Miss',
        content: 'Because this near-miss had catastrophic potential (S2, Track A), it receives a full investigation — the same rigor as if someone had actually been injured:',
        stages: [
          { status: 'New', day: 'Day 0', actor: 'mike', description: 'Mike reports the near-miss. System classifies as S2, Track A. Immediate notification sent to EHS manager.' },
          { status: 'Triage', day: 'Day 0', actor: 'sarah', description: 'Sarah escalates and assigns James as lead investigator within 2 hours.' },
          { status: 'Investigating', day: 'Day 1-7', actor: 'james', description: '5-Why root cause: no spotter protocol for aisle reversals, racking inspection overdue, no pedestrian barriers in forklift zones.' },
          { status: 'Awaiting CAPA', day: 'Day 8', actor: 'james', description: '3 CAPAs: (1) Spotter protocol for all reversals, (2) Physical barriers in high-traffic zones, (3) Monthly racking inspections.' },
          { status: 'Closed', day: 'Day 45', actor: 'sarah', description: 'All CAPAs verified effective. No repeat incidents in 30-day monitoring window.' },
        ],
      },
      {
        type: 'narrative',
        title: 'Why Near-Misses Matter Most',
        content: 'For every serious injury, there are roughly 30 near-misses. Reporting them is how you prevent the one that isn\'t a miss.',
        learnings: [
          'Near-misses use potential severity, not actual outcome',
          'High-potential near-misses get Track A — full investigation',
          'They generate the same CAPAs as actual injuries',
          'Near-miss data reveals systemic risks before people get hurt',
        ],
      },
    ],
  },

  {
    id: 'property_truck_hydrant',
    incidentType: 'property',
    title: 'The Truck and the Hydrant',
    subtitle: 'Learn property damage reporting and Track C auto-closure',
    setting: SETTINGS.warehouse,
    characters: ['priya'],
    estimatedMinutes: 5,
    difficulty: 'beginner',
    color: '#546E7A',
    icon: 'factory',
    coversModules: ['incidents'],
    learningOutcomes: [
      'Report property damage with estimated costs',
      'Understand Track C auto-close behavior',
      'Know when property damage should be escalated',
    ],
    chapters: [
      { title: 'The Scene', cards: [0] },
      { title: 'Reporting It', cards: [1, 2] },
      { title: 'The Outcome', cards: [3] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'A Costly Mistake in the Parking Lot',
        content: 'A delivery truck reverses over the kerb barrier in the east parking lot and strikes a fire hydrant. The water main ruptures, flooding the loading bay and shorting the electrical panel.',
        character: 'priya',
        quote: 'No one was hurt, thank goodness. But we had to shut down Loading Bay 2 for a full day while the electricians assessed the damage. Estimated repair cost: $15,000.',
        highlight: 'Property damage with no injury potential is typically low severity. But the cost and operational impact still need to be documented.',
      },
      {
        type: 'annotation',
        title: 'Reporting Property Damage',
        content: 'Priya opens the wizard and selects "Property Damage." The form asks for equipment/property affected and estimated cost.',
        annotation: 'Property damage reports focus on what was damaged, the cost estimate, and whether there were any secondary hazards (like the electrical panel shorting). These reports feed into cost-of-incidents analytics.',
        highlightType: 'property',
      },
      {
        type: 'exercise',
        title: 'Classify the Risk',
        content: 'A truck hit a hydrant, causing $15K in damage. No injuries, no injury potential.\n\n• Delivery area is typically clear of pedestrians\n• Electrical panel short was contained\n• Operational impact: 1 day loading bay shutdown',
        exerciseType: 'risk_matrix',
        correctLikelihood: 1,
        correctConsequence: 1,
        explanation: 'Likelihood "Unlikely" (rare backing incident) × Consequence "Minor" (property damage only, no injury risk) = **S4, Track C**. Track C means: logged for trend analysis, auto-closed, no investigation needed.',
      },
      {
        type: 'narrative',
        title: 'Track C: Log and Close',
        content: 'Track C incidents are automatically closed on creation. They\'re still recorded and counted in analytics — but they don\'t trigger an investigation workflow.',
        learnings: [
          'Property damage uses the same wizard — just a different type',
          'Track C = log and close (no investigation)',
          'Cost estimates feed into reports and trend analysis',
          'If there\'s any injury potential, escalate to a higher track',
        ],
        whatIfs: [
          { scenario: 'A pedestrian was in the loading bay when it flooded', result: 'Escalate to Near Miss, Track B or A depending on potential severity.' },
          { scenario: 'The electrical short started a fire', result: 'Multiple incident types: Property Damage + potentially Dangerous Occurrence if RIDDOR-reportable.' },
        ],
      },
    ],
  },

  {
    id: 'env_ibc_spill',
    incidentType: 'env',
    title: 'The IBC Spill',
    subtitle: 'Environmental release reporting and regulatory obligations',
    setting: SETTINGS.chemPlant,
    characters: ['mike', 'sarah', 'james'],
    estimatedMinutes: 8,
    difficulty: 'intermediate',
    color: '#2E7D32',
    icon: 'leaf',
    coversModules: ['incidents', 'investigations', 'capas'],
    learningOutcomes: [
      'Report environmental releases with substance details',
      'Understand containment and cleanup documentation',
      'Know regulatory reporting obligations',
    ],
    chapters: [
      { title: 'The Scene', cards: [0] },
      { title: 'The Incident', cards: [1] },
      { title: 'Reporting It', cards: [2, 3] },
      { title: 'The Response', cards: [4] },
      { title: 'The Outcome', cards: [5] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'Chemical Storage Area — Dawn Patrol',
        content: 'Mike arrives for the early shift and walks the chemical storage yard as part of his opening checks. Something\'s wrong — there\'s a strong solvent smell and a visible puddle beneath IBC #247.',
        character: 'mike',
        quote: 'I could smell it from 20 metres away. The bottom of the IBC had a hairline crack — solvent was pooling in the bund, but it was close to overtopping.',
      },
      {
        type: 'narrative',
        title: 'Containment Under Pressure',
        content: 'Approximately 200 litres of industrial solvent has leaked from the cracked IBC into the secondary containment bund. The bund is at 85% capacity — any more and the spill reaches bare soil.',
        character: 'mike',
        quote: 'I radioed Sarah immediately. We got the spill crew out in 15 minutes. They pumped the bund and started soil sampling around the perimeter.',
        highlight: 'Environmental releases require specific documentation: substance name, CAS number, estimated quantity, and containment status.',
      },
      {
        type: 'annotation',
        title: 'Environmental Release Reporting',
        content: 'Sarah reports this as an Environmental Release. The form captures chemical-specific data that may be needed for regulatory reporting.',
        annotation: 'The environmental form asks for: substance name, CAS/UN number, estimated quantity, release medium (air/water/soil), containment status (fully/partially/not contained), and cleanup actions taken.',
        highlightType: 'env',
        tip: 'Even if the spill was fully contained by a bund, it must still be reported. "Contained" doesn\'t mean "unreportable."',
      },
      {
        type: 'exercise',
        title: 'Classify the Risk',
        content: '200L solvent spill, partially contained in bund at 85% capacity. Consider:\n\n• Hazardous substance near soil/groundwater\n• Bund almost overtopped\n• No worker exposure (open-air area)\n• Cleanup crew required',
        exerciseType: 'risk_matrix',
        correctLikelihood: 2,
        correctConsequence: 3,
        explanation: 'Likelihood "Possible" (IBCs age and crack over time) × Consequence "Major" (environmental contamination risk, regulatory implications) = **S2, Track A**. Environmental releases with contamination potential always warrant full investigation.',
      },
      {
        type: 'lifecycle',
        title: 'Investigation & Regulatory Response',
        stages: [
          { status: 'New', day: 'Day 0', actor: 'sarah', description: 'Sarah reports the spill. System flags Track A with regulatory alert banner.' },
          { status: 'Investigating', day: 'Day 1-7', actor: 'james', description: 'Root cause: IBC past inspection date (18 months old, 12-month rated). No IBC inspection schedule existed.' },
          { status: 'Awaiting CAPA', day: 'Day 8', actor: 'james', description: 'CAPAs: (1) IBC inspection schedule every 6 months, (2) Bund capacity monitoring system, (3) Spill response drill quarterly.' },
          { status: 'Closed', day: 'Day 35', actor: 'sarah', description: 'Soil sampling clear, all CAPAs implemented and verified.' },
        ],
      },
      {
        type: 'narrative',
        title: 'Environmental Reporting Obligations',
        content: 'Environmental incidents often trigger regulatory reporting requirements beyond the internal EHS system.',
        learnings: [
          'Environmental releases require substance-specific documentation',
          'Containment status affects regulatory reporting obligations',
          'Even "contained" spills must be reported internally',
          'The system flags regulatory alerts to help EHS managers meet deadlines',
        ],
      },
    ],
  },

  {
    id: 'unsafe_exposed_wiring',
    incidentType: 'unsafe',
    title: 'The Exposed Wiring',
    subtitle: 'Proactive hazard reporting and stop-work authority',
    setting: SETTINGS.construction,
    characters: ['priya'],
    estimatedMinutes: 5,
    difficulty: 'beginner',
    color: '#1565C0',
    icon: 'shield',
    coversModules: ['incidents'],
    learningOutcomes: [
      'Report unsafe conditions before an incident occurs',
      'Understand the difference between unsafe conditions and near-misses',
      'Learn about stop-work authority',
    ],
    chapters: [
      { title: 'The Scene', cards: [0] },
      { title: 'Reporting It', cards: [1, 2] },
      { title: 'The Response', cards: [3] },
      { title: 'The Outcome', cards: [4] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'Daily Walk-Around — Level 2',
        content: 'Priya is conducting her daily walk-around on Level 2 of the construction site. Near the stairwell, she spots something dangerous: exposed electrical wiring in a wet area, with no barriers or warning signs.',
        character: 'priya',
        quote: 'Bare copper wires hanging near a puddle of rainwater. Someone could step in that water and get electrocuted. I stopped all work on Level 2 immediately.',
        highlight: 'No incident occurred — but the hazard is present and immediate. This is an Unsafe Condition, not a Near Miss (nothing happened yet).',
      },
      {
        type: 'annotation',
        title: 'Unsafe Condition vs Near Miss',
        content: 'Priya selects "Unsafe Condition" in the wizard. This is different from a near-miss.',
        annotation: 'Unsafe Condition: a hazard exists but no event has occurred yet. Near Miss: an event occurred but no one was harmed. The distinction matters because unsafe conditions are proactive — you\'re catching the hazard before anyone is exposed to it.',
        highlightType: 'unsafe',
        tip: 'Unsafe conditions are the most proactive reports. They represent hazards caught BEFORE they cause events. Encourage everyone to report them.',
      },
      {
        type: 'exercise',
        title: 'Classify the Risk',
        content: 'Exposed wiring in a wet area on an active construction site:\n\n• High voltage wiring accessible at ground level\n• Wet conditions increase electrocution risk\n• Workers pass through this area regularly\n• Potential for fatal electrocution',
        exerciseType: 'risk_matrix',
        correctLikelihood: 3,
        correctConsequence: 3,
        explanation: 'Likelihood "Likely" (workers pass through regularly, wet conditions common on construction sites) × Consequence "Major" (potential fatal electrocution) = **S2, Track A**. Stop-work was the right call.',
      },
      {
        type: 'lifecycle',
        title: 'Stop-Work and Rapid Resolution',
        stages: [
          { status: 'New', day: 'Day 0', actor: 'priya', description: 'Priya reports the unsafe condition with stop-work flag. Level 2 barricaded.' },
          { status: 'Investigating', day: 'Day 0', actor: 'james', description: 'Electrician inspects: temporary wiring from previous shift left unsecured. Isolated and made safe within 2 hours.' },
          { status: 'Awaiting CAPA', day: 'Day 1', actor: 'james', description: 'CAPA: mandatory end-of-shift lockout/tagout verification for all temporary electrical.' },
          { status: 'Closed', day: 'Day 7', actor: 'sarah', description: 'New procedure implemented and verified. Work on Level 2 resumed.' },
        ],
      },
      {
        type: 'narrative',
        title: 'The Power of Proactive Reporting',
        learnings: [
          'Unsafe conditions catch hazards BEFORE events happen',
          'Stop-work authority is every worker\'s right and responsibility',
          'Different from near-miss: no event occurred, just a hazard identified',
          'These reports build the most valuable prevention data',
        ],
      },
    ],
  },

  {
    id: 'observation_good_catch',
    incidentType: 'observation',
    title: 'The Good Catch',
    subtitle: 'Low-barrier safety observations and trend analysis',
    setting: SETTINGS.office,
    characters: ['mike'],
    estimatedMinutes: 4,
    difficulty: 'beginner',
    color: '#00897B',
    icon: 'eye',
    coversModules: ['incidents'],
    learningOutcomes: [
      'Make quick safety observations',
      'Understand positive vs concern observations',
      'See how observations feed trend analysis',
    ],
    chapters: [
      { title: 'The Scene', cards: [0] },
      { title: 'Reporting It', cards: [1] },
      { title: 'The Outcome', cards: [2] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'Server Room Check',
        content: 'An IT technician is doing routine maintenance in the server room. He notices the fire extinguisher has an expired inspection tag — last inspected 14 months ago, well past the 12-month cycle.',
        character: 'mike',
        quote: 'It\'s a small thing, but if there\'s ever a fire in here and that extinguisher doesn\'t work... I took 30 seconds to report it.',
        highlight: 'This isn\'t an emergency — it\'s an observation. The system makes it easy to log these in under a minute.',
      },
      {
        type: 'annotation',
        title: 'Quick and Easy Observation',
        content: 'In the wizard, select "Observation." The form is minimal — just describe what you observed and optionally suggest an action.',
        annotation: 'Observations are designed to be low-barrier. You don\'t need to know the risk matrix or fill out detailed forms. Just: what did you see, where, and what should be done about it.',
        highlightType: 'observation',
        tip: 'Observations can be positive too! "Great housekeeping in the welding bay" reinforces good behavior. It\'s not just about problems.',
      },
      {
        type: 'narrative',
        title: 'Every Observation Counts',
        content: 'This observation auto-closes as Track C (no investigation needed). But it\'s not lost — it appears in trend data. When the EHS manager pulls quarterly analytics, patterns emerge.',
        learnings: [
          'Observations take under a minute to submit',
          'Track C auto-close: no investigation, but still recorded',
          'Trend data reveals systemic issues (e.g., "fire equipment inspections overdue at 3 sites")',
          'Positive observations encourage safety culture',
        ],
        whatIfs: [
          { scenario: 'Multiple expired extinguishers across the building', result: 'Pattern triggers a facility-wide fire equipment audit — one observation can launch site-wide action.' },
        ],
      },
    ],
  },

  {
    id: 'dangerous_scaffold_collapse',
    incidentType: 'dangerous',
    title: 'The Scaffold Collapse',
    subtitle: 'Dangerous occurrences and RIDDOR regulatory obligations',
    setting: SETTINGS.construction,
    characters: ['priya', 'sarah', 'james'],
    estimatedMinutes: 8,
    difficulty: 'intermediate',
    color: '#B71C1C',
    icon: 'warning',
    coversModules: ['incidents', 'investigations', 'capas'],
    learningOutcomes: [
      'Identify RIDDOR-reportable dangerous occurrences',
      'Understand immediate notification requirements',
      'Handle high-severity Track A incidents',
    ],
    chapters: [
      { title: 'The Scene', cards: [0] },
      { title: 'The Incident', cards: [1] },
      { title: 'Reporting It', cards: [2, 3] },
      { title: 'The Response', cards: [4] },
      { title: 'The Outcome', cards: [5] },
    ],
    cards: [
      {
        type: 'narrative',
        title: 'Metro Construction Site 7 — High Winds',
        content: 'Weather warnings predicted gusts up to 45 mph. Work continues on the lower levels, but exterior scaffolding on Level 3 and above is off-limits.',
        character: 'priya',
        quote: 'We\'d already restricted access above Level 2. But what we didn\'t account for was loose materials left on the scaffold from the previous day.',
      },
      {
        type: 'narrative',
        title: 'The Plank Falls',
        content: 'A gust of wind dislodges a scaffold plank from Level 3. It falls 12 metres, landing in the barricaded exclusion zone below. The zone was correctly set up — no one was in it.',
        character: 'priya',
        quote: 'The barricade did its job. But a scaffold plank falling 12 metres is a dangerous occurrence under RIDDOR, regardless of whether anyone was in the zone.',
        highlight: 'This meets RIDDOR criteria for a dangerous occurrence: the collapse or partial collapse of scaffolding more than 5 metres high. It must be reported to HSE.',
      },
      {
        type: 'annotation',
        title: 'Dangerous Occurrence Reporting',
        content: 'In the wizard, select "Dangerous Occurrence." The form asks about the specific RIDDOR category and immediate actions taken.',
        annotation: 'Dangerous occurrences are defined by regulation — they\'re specific event types that must be reported to HSE even if no one was injured. The system helps you identify which RIDDOR category applies.',
        highlightType: 'dangerous',
        tip: 'RIDDOR dangerous occurrences require phone notification to HSE without delay, followed by a written F2508 form within 10 days.',
      },
      {
        type: 'exercise',
        title: 'Classify the Risk',
        content: 'Scaffold plank falls 12 metres into a barricaded zone:\n\n• Exclusion zone correctly established — no persons exposed\n• But: if the zone hadn\'t been set up, this would be fatal\n• Scaffold height exceeds 5m RIDDOR threshold\n• Weather conditions were forecast',
        exerciseType: 'risk_matrix',
        correctLikelihood: 2,
        correctConsequence: 4,
        explanation: 'Likelihood "Possible" (high winds + unsecured materials is a known combination) × Consequence "Catastrophic" (potential fatal injury) = **S1, Track A**. This is the highest severity — full investigation, immediate regulatory notification.',
      },
      {
        type: 'lifecycle',
        title: 'Regulatory Response + Investigation',
        stages: [
          { status: 'New', day: 'Day 0 (immediate)', actor: 'priya', description: 'Priya reports the dangerous occurrence. System flags S1, Track A with RIDDOR alert.' },
          { status: 'Triage', day: 'Day 0 (1 hour)', actor: 'sarah', description: 'Sarah calls HSE to report the dangerous occurrence by phone. Site partially shut down for scaffolding inspection.' },
          { status: 'Investigating', day: 'Day 1-10', actor: 'james', description: 'Full investigation: root cause is no end-of-shift material securing protocol for scaffolds. HSE F2508 submitted within 10 days.' },
          { status: 'Awaiting CAPA', day: 'Day 11', actor: 'james', description: 'CAPAs: (1) Wind protocol — secure all materials at 30mph forecast, (2) Pre-shift scaffold inspection checklist, (3) End-of-day scaffold securing sign-off.' },
          { status: 'Closed', day: 'Day 45', actor: 'sarah', description: 'All CAPAs implemented. HSE confirms no enforcement action. Incident closed.' },
        ],
      },
      {
        type: 'narrative',
        title: 'RIDDOR: What You Need to Know',
        content: 'Dangerous occurrences have strict regulatory timelines. The system helps ensure compliance.',
        learnings: [
          'Dangerous occurrences must be reported to HSE even without injuries',
          'Phone notification must happen without delay',
          'Written F2508 form must be submitted within 10 days',
          'The system tracks RIDDOR deadlines and generates reports',
          'S1 Track A triggers the most comprehensive investigation workflow',
        ],
      },
    ],
  },
];
