// server/services/pdf/generic_incident.js — WI-09 universal incident
// report PDF.
//
// Per PRD §4.6, this is the platform's fallback record artifact for
// any incident regardless of jurisdiction, classification, or
// completeness. It is NOT a regulatory submission — the footer makes
// that explicit. Where regulatory reporting is required, submit
// through the appropriate regulator's channels (OSHA ITA, HSE RIDDOR,
// SafeWork NSW Notify, etc.).
//
// Architectural notes:
//   • Reuses the pdfkit pattern from services/pdf/osha_300.js + 300a +
//     301: margins.bottom: 0, lineBreak: false on every text() call,
//     manual word-wrap via wrapLines() for free-text fields. See
//     memory feedback_pdfkit_autopagination for the rationale.
//   • Multi-page by design. Pagination is MANUAL — each draw helper
//     receives a cursor `y` and returns the new `y`, AND requests a
//     new page via the `nextPageIfNeeded()` helper when the next block
//     wouldn't fit.
//   • Section visibility is opt-in via the `sections` array; the route
//     defaults to all sections enabled.
//   • Customer-brandable: org name in the header, footer carries
//     "Generated by [platform] on [date]" + the internal-record
//     disclaimer. NO logo embedding — organizations table has no logo
//     column today, and the spec forbids external URL fetches.

import PDFDocument from 'pdfkit';
import { embedOrgLogo } from './logo.js';

const PAGE_OPTS = {
  layout: 'portrait',
  size: 'LETTER',
  margins: { top: 36, bottom: 0, left: 36, right: 36 },
};

const FONT_REG  = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';
const FONT_ITAL = 'Helvetica-Oblique';

const PAGE_W = 612;
const PAGE_H = 792;
const USABLE_W = PAGE_W - 72;
const LEFT_X = 36;

const HEADER_HEIGHT = 50;    // first-page header band; subsequent pages get a compact header
const FOOTER_RESERVE = 60;   // bottom region reserved for footer disclaimer

const PLATFORM_NAME = 'Safelync';

// ---------------------------------------------------------------------------
// Section visibility
// ---------------------------------------------------------------------------

export const ALL_SECTIONS = [
  'overview',
  'affected_persons',
  'investigation',
  'causes',
  'capas',
  'classifications',
  'attachments',
  'audit',
];

// ---------------------------------------------------------------------------
// Low-level helpers (manual layout — no auto-pagination)
// ---------------------------------------------------------------------------

function fmt(value) {
  if (value === null || value === undefined || value === '') return 'Not recorded';
  return String(value);
}

function fmtDateTime(iso) {
  if (!iso) return 'Not recorded';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toISOString().slice(0, 16).replace('T', ' ');
}

function fmtDate(iso) {
  if (!iso) return 'Not recorded';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toISOString().slice(0, 10);
}

// Word-wrap helper — emits each line with lineBreak: false so pdfkit
// never auto-paginates mid-paragraph. Returns the lines as an array;
// caller is responsible for drawing them at known y coordinates.
function wrapLines(doc, text, width, font, fontSize) {
  if (!text) return [];
  doc.font(font).fontSize(fontSize);
  const paragraphs = String(text).split(/\r?\n/);
  const lines = [];
  for (const para of paragraphs) {
    const words = para.split(/\s+/).filter(Boolean);
    if (words.length === 0) { lines.push(''); continue; }
    let cur = '';
    for (const word of words) {
      const tentative = cur ? `${cur} ${word}` : word;
      if (doc.widthOfString(tentative) <= width) {
        cur = tentative;
      } else {
        if (cur) lines.push(cur);
        cur = word;
      }
    }
    if (cur) lines.push(cur);
  }
  return lines;
}

function drawWrapped(doc, x, y, width, text, fontSize = 9, color = '#000000', font = FONT_REG) {
  const lineH = fontSize + 3;
  const lines = wrapLines(doc, text, width, font, fontSize);
  doc.font(font).fontSize(fontSize).fillColor(color);
  for (let i = 0; i < lines.length; i++) {
    doc.text(lines[i], x, y + i * lineH, { width, lineBreak: false });
  }
  return y + lines.length * lineH;
}

// Page-overflow guard: if drawing `neededHeight` from the current `y`
// would land past the safe zone (page.height - FOOTER_RESERVE), add a
// new page and reset y to the post-header band. Returns the new y.
function nextPageIfNeeded(doc, y, neededHeight, ctx) {
  if (y + neededHeight <= PAGE_H - FOOTER_RESERVE) return y;
  doc.addPage(PAGE_OPTS);
  ctx.pageIndex += 1;
  drawCompactHeader(doc, ctx);
  return 70;
}

function drawSectionHeader(doc, x, y, w, text, ctx) {
  // Reserve space for the section header itself + a small content
  // breath so we don't orphan a section title at page bottom.
  y = nextPageIfNeeded(doc, y, 32, ctx);
  doc.save();
  doc.lineWidth(0.6).strokeColor('#000000');
  doc.rect(x, y, w, 16).fillAndStroke('#E8E8EE', '#000000');
  doc.fillColor('#000000').font(FONT_BOLD).fontSize(10);
  doc.text(text, x + 4, y + 4, { width: w - 8, lineBreak: false });
  doc.restore();
  return y + 18;
}

function drawFieldRow(doc, x, y, w, label, value, ctx) {
  y = nextPageIfNeeded(doc, y, 22, ctx);
  doc.save();
  doc.font(FONT_BOLD).fontSize(8).fillColor('#52525F');
  doc.text(label, x, y, { width: w * 0.32, lineBreak: false, ellipsis: true });
  doc.font(FONT_REG).fontSize(9).fillColor('#1A1A1A');
  // Allow the value to wrap onto multiple lines if needed.
  const lines = wrapLines(doc, fmt(value), w * 0.65, FONT_REG, 9);
  for (let i = 0; i < lines.length; i++) {
    doc.text(lines[i], x + w * 0.35, y + i * 12, { width: w * 0.65, lineBreak: false });
  }
  doc.restore();
  return y + Math.max(12, lines.length * 12) + 4;
}

function drawSubsectionLabel(doc, x, y, text, ctx) {
  y = nextPageIfNeeded(doc, y, 18, ctx);
  doc.font(FONT_BOLD).fontSize(8).fillColor('#52525F');
  doc.text(text, x, y, { width: USABLE_W, lineBreak: false });
  return y + 12;
}

function drawSeparator(doc, x, y, w) {
  doc.save();
  doc.lineWidth(0.3).strokeColor('#E0E0E0');
  doc.moveTo(x, y).lineTo(x + w, y).stroke();
  doc.restore();
  return y + 6;
}

// ---------------------------------------------------------------------------
// Page chrome
// ---------------------------------------------------------------------------

function drawFirstPageHeader(doc, ctx) {
  const { orgName, incident, orgLogoPath } = ctx;
  doc.save();

  // Logo slot: top-right, 80px wide × 40px tall. No-op when unset.
  const LOGO_W = 90;
  const LOGO_H = 40;
  embedOrgLogo(doc, orgLogoPath, PAGE_W - LEFT_X - LOGO_W, 32, LOGO_W, LOGO_H);

  doc.font(FONT_BOLD).fontSize(16).fillColor('#1A1A1A');
  doc.text(orgName || PLATFORM_NAME, LEFT_X, 36, { width: USABLE_W - LOGO_W - 20, lineBreak: false, ellipsis: true });

  doc.font(FONT_BOLD).fontSize(11).fillColor('#52525F');
  doc.text('Incident Report', LEFT_X, 58, { width: USABLE_W - LOGO_W - 20, lineBreak: false });

  doc.font(FONT_REG).fontSize(9).fillColor('#52525F');
  const subRight = `${incident.incident_number}${incident.title ? ' — ' + incident.title : ''}`;
  doc.text(subRight, LEFT_X, 74, { width: USABLE_W - LOGO_W - 20, lineBreak: false, ellipsis: true });
  doc.restore();
}

function drawCompactHeader(doc, ctx) {
  const { orgName, incident, pageIndex } = ctx;
  doc.save();
  doc.font(FONT_BOLD).fontSize(9).fillColor('#52525F');
  doc.text(
    `${orgName || PLATFORM_NAME} — ${incident.incident_number}`,
    LEFT_X, 28, { width: USABLE_W * 0.75, lineBreak: false, ellipsis: true },
  );
  doc.font(FONT_REG).fontSize(8).fillColor('#666A72');
  doc.text(`Page ${pageIndex}`, LEFT_X, 28, { width: USABLE_W, align: 'right', lineBreak: false });
  doc.restore();
}

function drawFooter(doc, generatedAt) {
  doc.save();
  const y = PAGE_H - 36;
  doc.font(FONT_REG).fontSize(7).fillColor('#666A72');
  doc.text(
    `Generated by ${PLATFORM_NAME} on ${generatedAt}`,
    LEFT_X, y, { width: USABLE_W, align: 'center', lineBreak: false },
  );
  doc.font(FONT_ITAL).fontSize(7).fillColor('#666A72');
  doc.text(
    'This document is an internal record and is not a regulatory submission. ' +
    'Where regulatory reporting is required, submit through the appropriate regulator\'s channels ' +
    '(OSHA ITA, HSE RIDDOR, SafeWork NSW Notify).',
    LEFT_X, y + 10, { width: USABLE_W, align: 'center', lineBreak: false },
  );
  doc.restore();
}

// ---------------------------------------------------------------------------
// Sections — each takes the payload and returns the new y cursor.
// Every section is a no-op (returns y unchanged) when its source data
// is absent.
// ---------------------------------------------------------------------------

function sectionOverview(doc, y, ctx) {
  const { incident, site } = ctx;
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Incident overview', ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Number',         incident.incident_number, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Title',          incident.title, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Type',           incident.type, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Severity',       incident.severity != null ? `S${incident.severity}` : null, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Track',          incident.track, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Status',         incident.status, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Incident date',  fmtDateTime(incident.incident_datetime), ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Site',           site?.name, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Area / location', [incident.area, incident.specific_location].filter(Boolean).join(' · ') || null, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Department',     incident.department, ctx);
  if (incident.description) {
    y = drawSubsectionLabel(doc, LEFT_X, y + 4, 'Description', ctx);
    y = nextPageIfNeeded(doc, y, 36, ctx);
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, incident.description, 9, '#1A1A1A', FONT_REG);
  }
  if (incident.immediate_actions_taken) {
    y = drawSubsectionLabel(doc, LEFT_X, y + 6, 'Immediate actions taken', ctx);
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, incident.immediate_actions_taken, 9, '#1A1A1A', FONT_REG);
  }
  return y + 12;
}

function sectionAffectedPersons(doc, y, ctx) {
  const { affectedPersons } = ctx;
  if (!Array.isArray(affectedPersons) || affectedPersons.length === 0) {
    // Render the header + "Not recorded" rather than hide entirely —
    // an inspector wants to see the section was checked, just empty.
    y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Affected persons', ctx);
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, 'No affected persons recorded for this incident.', 9, '#666A72', FONT_ITAL);
    return y + 8;
  }
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Affected persons', ctx);
  for (let i = 0; i < affectedPersons.length; i++) {
    const ap = affectedPersons[i];
    y = nextPageIfNeeded(doc, y, 60, ctx);
    doc.save();
    doc.font(FONT_BOLD).fontSize(10).fillColor('#1A1A1A');
    doc.text(
      `${i + 1}. ${ap.name || 'Unnamed'}${ap.is_primary ? ' · primary' : ''}`,
      LEFT_X, y, { width: USABLE_W, lineBreak: false, ellipsis: true },
    );
    doc.restore();
    y += 14;
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Job title',          ap.job_title, ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Employment status',  ap.employment_status, ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Date of birth',      fmtDate(ap.dob), ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Date hired',         fmtDate(ap.date_hired), ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Privacy case',       ap.is_privacy_case ? 'Yes' : 'No', ctx);
    if (Array.isArray(ap.injuries) && ap.injuries.length > 0) {
      y = drawSubsectionLabel(doc, LEFT_X, y + 4, 'Injuries', ctx);
      for (const inj of ap.injuries) {
        y = drawFieldRow(doc, LEFT_X + 16, y, USABLE_W - 16, 'Body part',     inj.body_part, ctx);
        y = drawFieldRow(doc, LEFT_X + 16, y, USABLE_W - 16, 'Injury type',   inj.injury_type, ctx);
        y = drawFieldRow(doc, LEFT_X + 16, y, USABLE_W - 16, 'Mechanism',     inj.mechanism, ctx);
        y = drawFieldRow(doc, LEFT_X + 16, y, USABLE_W - 16, 'Treatment',     inj.treatment, ctx);
        y = drawFieldRow(doc, LEFT_X + 16, y, USABLE_W - 16, 'ER treated',    inj.er_treated ? 'Yes' : 'No', ctx);
        y = drawFieldRow(doc, LEFT_X + 16, y, USABLE_W - 16, 'Hospitalized',  inj.hospitalized ? 'Yes' : 'No', ctx);
        if (inj.date_of_death) {
          y = drawFieldRow(doc, LEFT_X + 16, y, USABLE_W - 16, 'Date of death', fmtDate(inj.date_of_death), ctx);
        }
        y = drawSeparator(doc, LEFT_X + 16, y, USABLE_W - 16);
      }
    }
    y = drawSeparator(doc, LEFT_X, y, USABLE_W);
  }
  return y + 6;
}

function sectionInvestigation(doc, y, ctx) {
  const { investigation, investigationLead } = ctx;
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Investigation findings', ctx);
  if (!investigation) {
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, 'No investigation opened for this incident.', 9, '#666A72', FONT_ITAL);
    return y + 8;
  }
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Number',     investigation.investigation_number, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Status',     investigation.status, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Track',      investigation.track, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Lead',       investigationLead?.name, ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Started',    fmtDateTime(investigation.started_at), ctx);
  y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Due',        fmtDate(investigation.due_date), ctx);
  if (investigation.closed_at) {
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Closed',     fmtDateTime(investigation.closed_at), ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Close reason', investigation.closed_reason, ctx);
  }
  if (investigation.findings) {
    y = drawSubsectionLabel(doc, LEFT_X, y + 4, 'Findings', ctx);
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, investigation.findings, 9, '#1A1A1A', FONT_REG);
  }
  if (investigation.root_cause_summary) {
    y = drawSubsectionLabel(doc, LEFT_X, y + 6, 'Root cause summary', ctx);
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, investigation.root_cause_summary, 9, '#1A1A1A', FONT_REG);
  }
  return y + 8;
}

function sectionCauses(doc, y, ctx) {
  const { fiveWhys, investigation } = ctx;
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Root cause analysis', ctx);
  // Categories carried on the investigation row itself (WI-A / activity log).
  let categories = [];
  try { categories = JSON.parse(investigation?.root_cause_categories || '[]'); } catch (_) {}
  if (categories.length > 0) {
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Categories', categories.join(' · '), ctx);
  }
  if (!Array.isArray(fiveWhys) || fiveWhys.length === 0) {
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, 'No 5-Why chain recorded.', 9, '#666A72', FONT_ITAL);
    return y + 8;
  }
  y = drawSubsectionLabel(doc, LEFT_X, y + 4, '5-Why chain', ctx);
  for (const w of fiveWhys) {
    y = nextPageIfNeeded(doc, y, 30, ctx);
    doc.font(FONT_BOLD).fontSize(8).fillColor('#52525F');
    doc.text(`Why #${w.level}${w.is_root_cause ? ' · ROOT CAUSE' : ''}`, LEFT_X, y, { width: USABLE_W, lineBreak: false });
    y += 11;
    y = drawWrapped(doc, LEFT_X + 8, y, USABLE_W - 8, `Q: ${w.question || ''}`, 9, '#1A1A1A', FONT_REG);
    y = drawWrapped(doc, LEFT_X + 8, y + 2, USABLE_W - 8, `A: ${w.answer || ''}`, 9, '#1A1A1A', FONT_REG);
    y += 4;
  }
  return y + 6;
}

function sectionCapas(doc, y, ctx) {
  const { capas } = ctx;
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Corrective & preventive actions (CAPAs)', ctx);
  if (!Array.isArray(capas) || capas.length === 0) {
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, 'No CAPAs linked to this incident.', 9, '#666A72', FONT_ITAL);
    return y + 8;
  }
  for (let i = 0; i < capas.length; i++) {
    const c = capas[i];
    y = nextPageIfNeeded(doc, y, 60, ctx);
    doc.font(FONT_BOLD).fontSize(10).fillColor('#1A1A1A');
    doc.text(
      `${i + 1}. ${c.capa_number}${c.title ? ' — ' + c.title : ''}`,
      LEFT_X, y, { width: USABLE_W, lineBreak: false, ellipsis: true },
    );
    y += 14;
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Type',      c.type, ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Priority',  c.priority, ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Status',    c.status, ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Owner',     c.owner_name, ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Verifier',  c.verifier_name, ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Due',       fmtDate(c.due_date), ctx);
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Progress',  c.progress != null ? `${c.progress}%` : null, ctx);
    if (c.description) {
      y = drawSubsectionLabel(doc, LEFT_X, y + 2, 'Description', ctx);
      y = drawWrapped(doc, LEFT_X, y, USABLE_W, c.description, 9, '#1A1A1A', FONT_REG);
    }
    y = drawSeparator(doc, LEFT_X, y + 4, USABLE_W);
  }
  return y + 6;
}

function sectionClassifications(doc, y, ctx) {
  const { incident, oshaSevereRows, riddorReport, nswNotification } = ctx;
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Regulatory classifications', ctx);

  let any = false;

  // OSHA recordability
  if (incident.osha_recordable !== null && incident.osha_recordable !== undefined) {
    any = true;
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'OSHA recordable',
      incident.osha_recordable ? `Yes (${incident.osha_recordability_type || ''})` : 'No', ctx);
    if (incident.osha_recordable) {
      y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Days away',    incident.osha_days_away, ctx);
      y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Days restricted', incident.osha_days_restricted, ctx);
      if (incident.osha_date_of_death) {
        y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'Date of death', fmtDate(incident.osha_date_of_death), ctx);
      }
    }
  }

  // OSHA 1904.39 severe-injury notifications
  if (Array.isArray(oshaSevereRows) && oshaSevereRows.length > 0) {
    any = true;
    y = drawSubsectionLabel(doc, LEFT_X, y + 4, '1904.39 severe-injury notifications', ctx);
    for (const r of oshaSevereRows) {
      y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8,
        r.category, `Deadline ${fmtDateTime(r.deadline_at)} · ${r.phone_notified_at ? 'Phone notified ' + fmtDateTime(r.phone_notified_at) : 'Phone pending'}`, ctx);
    }
  }

  // RIDDOR
  if (incident.riddor_reportable || riddorReport) {
    any = true;
    y = drawFieldRow(doc, LEFT_X, y, USABLE_W, 'RIDDOR reportable',
      incident.riddor_reportable ? `Yes${incident.riddor_category ? ` (${incident.riddor_category})` : ''}` : 'No', ctx);
    if (riddorReport) {
      y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Reference', riddorReport.riddor_number, ctx);
      y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Phone notified', fmtDateTime(riddorReport.phone_notified_at), ctx);
      y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Written submitted', fmtDateTime(riddorReport.written_submitted_at), ctx);
      y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Written deadline', fmtDateTime(riddorReport.written_deadline), ctx);
    }
  }

  // SafeWork NSW
  if (nswNotification) {
    any = true;
    y = drawSubsectionLabel(doc, LEFT_X, y + 4, 'SafeWork NSW notification', ctx);
    y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'NSW number',   nswNotification.nsw_number, ctx);
    y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Fatality',     nswNotification.is_fatality ? 'Yes' : 'No', ctx);
    y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Serious injury', nswNotification.is_serious_injury ? 'Yes' : 'No', ctx);
    y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Dangerous incident', nswNotification.is_dangerous_incident ? 'Yes' : 'No', ctx);
    y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Phone notified', fmtDateTime(nswNotification.phone_notified_at), ctx);
    y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Written submitted', fmtDateTime(nswNotification.written_submitted_at), ctx);
    y = drawFieldRow(doc, LEFT_X + 8, y, USABLE_W - 8, 'Site preservation', nswNotification.site_preservation_status, ctx);
  }

  if (!any) {
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, 'No regulatory classifications recorded.', 9, '#666A72', FONT_ITAL);
  }
  return y + 8;
}

function sectionAttachments(doc, y, ctx) {
  const { attachments } = ctx;
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Attachments', ctx);
  if (!Array.isArray(attachments) || attachments.length === 0) {
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, 'No attachments uploaded.', 9, '#666A72', FONT_ITAL);
    return y + 8;
  }
  for (const a of attachments) {
    y = nextPageIfNeeded(doc, y, 16, ctx);
    doc.font(FONT_BOLD).fontSize(8).fillColor('#1A1A1A');
    doc.text(`• ${a.filename}`, LEFT_X, y, { width: USABLE_W * 0.55, lineBreak: false, ellipsis: true });
    doc.font(FONT_REG).fontSize(8).fillColor('#666A72');
    const meta = [
      a.mime_type,
      a.size_bytes ? `${Math.round(a.size_bytes / 1024)} KB` : null,
      a.created_at ? fmtDate(a.created_at) : null,
    ].filter(Boolean).join(' · ');
    doc.text(meta, LEFT_X + USABLE_W * 0.6, y, { width: USABLE_W * 0.4, align: 'right', lineBreak: false, ellipsis: true });
    if (a.description) {
      y += 11;
      y = drawWrapped(doc, LEFT_X + 12, y, USABLE_W - 12, a.description, 8, '#52525F', FONT_REG);
    } else {
      y += 12;
    }
    y += 2;
  }
  return y + 6;
}

function sectionAudit(doc, y, ctx) {
  const { auditEntries } = ctx;
  y = drawSectionHeader(doc, LEFT_X, y, USABLE_W, 'Audit trail (most recent entries)', ctx);
  if (!Array.isArray(auditEntries) || auditEntries.length === 0) {
    y = drawWrapped(doc, LEFT_X, y, USABLE_W, 'No audit entries.', 9, '#666A72', FONT_ITAL);
    return y + 8;
  }
  for (const e of auditEntries) {
    y = nextPageIfNeeded(doc, y, 18, ctx);
    doc.font(FONT_REG).fontSize(7).fillColor('#666A72');
    doc.text(fmtDateTime(e.created_at), LEFT_X, y, { width: 110, lineBreak: false });
    doc.font(FONT_BOLD).fontSize(7).fillColor('#1A1A1A');
    doc.text(e.action || '', LEFT_X + 110, y, { width: 130, lineBreak: false, ellipsis: true });
    doc.font(FONT_REG).fontSize(7).fillColor('#1A1A1A');
    const desc = `${e.user_name ? '[' + e.user_name + '] ' : ''}${e.description || ''}`;
    const lines = wrapLines(doc, desc, USABLE_W - 240, FONT_REG, 7);
    for (let i = 0; i < lines.length; i++) {
      doc.text(lines[i], LEFT_X + 240, y + i * 9, { width: USABLE_W - 240, lineBreak: false });
    }
    y += Math.max(10, lines.length * 9) + 2;
  }
  return y + 6;
}

const SECTION_FN = {
  overview:         sectionOverview,
  affected_persons: sectionAffectedPersons,
  investigation:    sectionInvestigation,
  causes:           sectionCauses,
  capas:            sectionCapas,
  classifications:  sectionClassifications,
  attachments:      sectionAttachments,
  audit:            sectionAudit,
};

// ---------------------------------------------------------------------------
// Public entrypoint
// ---------------------------------------------------------------------------

/**
 * Stream the generic incident PDF to `res`. The route layer loads all
 * the payload pieces (incident, site, AP+injuries, investigation,
 * fiveWhys, capas, classifications, attachments, auditEntries, orgName)
 * and passes them here.
 *
 *   payload = {
 *     orgName, site,
 *     incident,                  // joined row
 *     affectedPersons: [...],    // each with injuries: [...]
 *     investigation, investigationLead, fiveWhys,
 *     capas,                     // with owner_name + verifier_name resolved
 *     oshaSevereRows, riddorReport, nswNotification,
 *     attachments,
 *     auditEntries,
 *     sections: ['overview', ...],  // which to render; defaults to ALL_SECTIONS
 *     generatedAt,               // ISO string for the footer
 *   }
 */
export function renderGenericIncidentPdf(res, payload) {
  // Section filter — default ALL_SECTIONS. If the caller passed a
  // non-empty list whose every entry is unknown, fall back to defaults
  // rather than rendering an empty document. Mirrors the same fallback
  // the route applies, but enforces it here too so direct callers
  // (tests, future integrations) get the same behaviour.
  let sections = ALL_SECTIONS;
  if (Array.isArray(payload.sections) && payload.sections.length > 0) {
    const filtered = payload.sections.filter(s => SECTION_FN[s]);
    if (filtered.length > 0) sections = filtered;
  }

  const doc = new PDFDocument(PAGE_OPTS);
  doc.pipe(res);

  const ctx = {
    orgName: payload.orgName,
    orgLogoPath: payload.orgLogoPath || null,
    incident: payload.incident,
    site: payload.site,
    affectedPersons: payload.affectedPersons,
    investigation: payload.investigation,
    investigationLead: payload.investigationLead,
    fiveWhys: payload.fiveWhys,
    capas: payload.capas,
    oshaSevereRows: payload.oshaSevereRows,
    riddorReport: payload.riddorReport,
    nswNotification: payload.nswNotification,
    attachments: payload.attachments,
    auditEntries: payload.auditEntries,
    pageIndex: 1,
  };

  drawFirstPageHeader(doc, ctx);
  let y = 100;

  for (const sec of sections) {
    const fn = SECTION_FN[sec];
    if (!fn) continue;
    y = fn(doc, y, ctx);
  }

  // Footer on the LAST page only. The internal-record disclaimer is
  // the same on every page; running it once at the end keeps the body
  // surface uncluttered while still surfacing the legal notice.
  drawFooter(doc, payload.generatedAt || new Date().toISOString().slice(0, 10));

  doc.end();
}
